services:
  db:
    #mariadb supposed to support more architectures
    image: mariadb:10.9
    #authentication plugin for mariadb..outdated?
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:6.0
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wp
volumes:
  db_data:
  wp_data: